### ISSUE TITLE
wiring

### ISSUE THREAD

**Issue by jannikbussmann** [mtedaldi/PyFanControl#1]
could you provide some informations about the wiring? I want to control a sinamics g110 with raspberry pi over a MCP4725 and I´m really interested how you have done this.

**Comment by mtedaldi** [comment]
The wiring is kept as simple as possible. So I made a 4 pin connector with 4 wires (Vcc, GND, Clk, Data) und put the ICs on little PCB.
That's the I2C side (I made sure I had everything on 3.3V, so I could connect directly to the RasPi).

For the analogue side I used the +10V from the connector of the G110 to provide the voltage for the DAC, connected GND and wired the output of the DAC to the input of the G110.
This is all just from the top of my head (I haven't looked at that project in years).

**Comment by mtedaldi** [comment]
Since there were no further questions i consider this resolved.
